### ISSUE TITLE
Rewrite OAuth Bundle to Serverless

### ISSUE THREAD

**Issue by MiroCillik** [keboola/oauth-api#1]
- [x] Tests
- [x] KBC Token authorization
- [x] Encryption
- [x] Consumer endpoint
- [x] Auth endpoint
- [x] Credentials endpoint
- [x] Travis CI
- [x] Session management
- [x] Error handling and error message
- [x] More secure Session, hash the session ID, add proper expiration and check
- [x] Custom OAuth - Facebook
- [x] Custom OAuth - Quickbooks
- [x] Custom OAuth - 1.0
- [x] Modify DockerRunner to specify which version of oauth to run in config
- [x] Deploy to Test env
- [ ] UI preparations for dark launch
- [ ] Dark launch mechanism
- [ ] Deploy to Prod env (dark launch)
- [ ] Beta testing
- [ ] Full launch, replace the old api

**Comment by MiroCillik** [comment]
Waiting for https://github.com/keboola/docker-bundle/issues/232

**Comment by odinuv** [comment]
Nah, waiting for https://github.com/keboola/connection/issues/1165 :)

**Comment by MiroCillik** [comment]
Let's continue in https://github.com/keboola/oauth-api/issues/83 and I'm closing it here.
