### ISSUE TITLE
Register callback urls for all apps

### ISSUE THREAD

**Issue by MiroCillik** [keboola/oauth-api#100]
This has to be done manually.

List of apps:
https://sites.google.com/keboola.com/devel-internal/komponenty/oauth/registrovan%C3%A9-oauth-komponenty?authuser=0

- [x] esnerda.ex-bingads
- [ ] esnerda.ex-twitter-ads (private)
- [ ] kds.ex-ca-rally (doesnt use oauth, API key is directly inserted into config)
- [x] keboola.ex-facebook
- [x] keboola.ex-facebook-ads
- [x] keboola.ex-instagram
- [x] medio.wr-google-analytics-data-import
- [x] keboola.ex-gcalendar
- [x] keboola.ex-gmail
- [x] keboola.ex-google-adwords-reports-v201802
- [x] keboola.ex-google-analytics-v4 (US)
- [x] keboola.ex-google-analytics-v4 (EU)
- [x] keboola.ex-google-bigquery
- [x] keboola.ex-google-drive (US)
- [x] keboola.ex-google-drive (EU)
- [x] keboola.ex-googleplus
- [x] keboola.ex-intercom-v2
- [ ] keboola.ex-linkedin (zrejme to iste ako leochan's)
- [x] leochan.ex-linkedin
- [x] keboola.ex-mediamath (je private, nepouziva sa, myslim, ze ani nie je funkcny https://keboola.zendesk.com/agent/tickets/5969)
- [x] keboola.ex-slack
- [x] keboola.ex-strava (Appka založená Najlošem (pod jeho accountem) pro Matějkysovo pokusy.)
- [x] keboola.ex-twitter
- [x] keboola.ex-youtube
- [x] keboola.wr-dropbox-v2
- [x] keboola.wr-google-bigquery
- [x] keboola.wr-google-drive
- [x] keboola.wr-google-sheets
- [ ] leochan.ex-quickbooks
- [x] medio.wr-google-analytics-costs (deprecated: https://components.keboola.com/admin/components/medio.wr-google-analytics-costs)
- [x] pocin.ex-bingads (private)
- [x] pocin.ex-esplanade-onedrive-offline-reports (private)
- [x] sun.ex-mcf-api (private)
- [x] medio.ex-google-search-console
- [x] vokurka.ex-xero (manual config)
- [x] esnerda.ex-gmail-csv-downloader (private)
- [x] jakub-bartel.ex-onedrive
- [x] pocin.ex-gmail-attachments (deprecated)
- [x] apac.ex-gmail-attachments
- [x] esnerda.wr-zoho-crm - ~bude treba zalozit nove apky pre vsetky 3 regiony~ - zalozene - https://accounts.zoho.eu/developerconsole (private)
- [x] pocin.wr-google-doubleclick-bid-manager (neexistuje, existuje len apac.ex-google-doubleclick-bid-manager, ale ten nie je registrovany v OAuth api)
- [x] apac.ex-xero (private)
- [ ] MYOB AccountRight

**Comment by MiroCillik** [comment]
Some of the services only allow one redirect url per app. So existing configurations will not work with new OAuth :(

**Comment by Halama** [comment]
Které jsou teda ty které podporují jenom jeden redirect? Ty budeme muset založit znovu, nebude je přepisovat consumers migrace a uživatelé při migraci budou muset reautorizovat konfiguraci.

**Comment by MiroCillik** [comment]
Tieto komponenty su "problemove" a budu sa musiet reautorizovat. Vacs

- [ ] esnerda.ex-bingads - zalozene nove creds pre vsetky 3 regiony pod keboola.dev@outlook.com
- [ ] esnerda.ex-twitter-ads (private) - zalozit novu apku v regione US, pouziva sa len tam
- [ ] keboola.ex-slack - ziskat pristup od Padaka? Alebo zalozit nove creds
- [ ] vokurka.ex-xero - skontrolovat
- [ ] esnerda.wr-zoho-crm - nove klice
- [ ] apac.ex-xero - skontrolovat

**Comment by MiroCillik** [comment]
Po migracii Consumers, prejst tento zoznam a pridat chybajuce (nove) public apky do EU a AP regionov.
Private apky pridat do prislusnych regionov: 
`esnerda.wr-zoho-crm` - private - US

**Comment by MiroCillik** [comment]
David Esner este stale nepridal redirec uris pre `esnerda.ex-twitter-ads`. https://keboola.slack.com/archives/C0M08KNLR/p1540908360001900

**Comment by Halama** [comment]
Github mě v EU s nastavenou feature pro nový oauth hodí sem:
![image](https://user-images.githubusercontent.com/903531/48199056-31183800-e35b-11e8-95a7-f6bad5d1f658.png)

**Comment by Halama** [comment]
Twitter EU
![image](https://user-images.githubusercontent.com/903531/48199742-5ad25e80-e35d-11e8-9254-09fe7740b983.png)

**Comment by MiroCillik** [comment]
Nakoniec by to mali byt len tieto dve obskurne:

> Tieto komponenty su "problemove" a budu sa musiet reautorizovat.
> 
> * [ ]  esnerda.ex-twitter-ads (private) - hodil som na Davida Esnera, nech tam prida nove urls
> * [x]  esnerda.wr-zoho-crm - nove klice pre vsetky regiony (je private, staci len US)
> 
> Weird, but no action required:
> 
> * vokurka.ex-xero - nema redirect URL :/
> * apac.ex-xero - dtto, nepouziva sa, potrebuje OAuth 1.0 + RSA, ak budu chciet tak sa ozvu
> 
> UPDATE: takze nakoniec nie potreba ziadna vynimka v migracii Consumers

Ale je mozne, ze to v tom EU bolo zaregistrovane nejak podivne. Mrknem na to.

**Comment by MiroCillik** [comment]
EU Twitter som fixol, zalozil som novu apku pod `@KeboolaDev` https://developer.twitter.com/en/apps/15954048.

**Comment by MiroCillik** [comment]
A zmenil som to aj v starom OAuthe, takze keby sa znovu spustila migracia, bude to OK.
