### ISSUE TITLE
Setup papertrail searches for production stacks

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#108]
Setup error search with alerts to #support_maintenance

![image](https://user-images.githubusercontent.com/903531/47156753-0ef54200-d2e8-11e8-9cae-d90cc40e7e2b.png)

**Comment by Halama** [comment]
Tohle by měl být internal error, vrací to 502. Nevím jak se to z toho pozná.
Taky je ten log nějak divně rozeskaný na více řádků.
![image](https://user-images.githubusercontent.com/903531/47158219-7660c100-d2eb-11e8-8d50-ebff5a2420c5.png)

**Comment by Halama** [comment]
Ještě v logu vidím tyhle věci:
```
Oct 18 15:40:16 oauth-api prod: 2018-10-18T13:40:15.345Z 545223be-d2db-11e8-b2a1-2ffff6dab242 Task timed out after 6.01 seconds
```

**Comment by MiroCillik** [comment]
Ta chyba `UnhandledPromiseRejectionWarning` bude zrejme suvisiet s https://github.com/keboola/serverless-request-handler/pull/1

**Comment by MiroCillik** [comment]
Zalozeny search, tie chyby vyzera, ze uz sa formatuju spravne:
https://papertrailapp.com/searches/50782862/edit

Este sa pozabavam s tym timeoutom taskov.

**Comment by Halama** [comment]
ok, tak na ty timeout založ nové issue at se tohle může zavřít

**Comment by MiroCillik** [comment]
Dobre issue je tu https://github.com/keboola/oauth-api/issues/116.
Tuto zatvaram.
