### ISSUE TITLE
Performance tests and settings

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#109]
Je potřeba ověřit jakou to zvládne zátěž. Testoval bych hlavně [get credentials](https://keboolaoauthapiv3.docs.apiary.io/#reference/0/credentialscomponentidname/credentials-detail) které se volají v rámci běhu jobů a musí být stabiliní.

Jaký je rate limiting api gateway?
Jak je nastavená propustnost dynama?  
Vidím že se zatím neřeší https://github.com/keboola/oauth-api/blob/5e9d0f7e191ea7fa65d474a64465df5371ce58ea/serverless.yml#L167 Může to být jako parametr toho stacku nebo ideální by bylo prozkoumat https://aws.amazon.com/blogs/aws/new-auto-scaling-for-amazon-dynamodb/ jestli by byl použitelný at se to nemusí zbytečně ladit nebo pálit $ navíc v době menšího trafficu.

Taky by se měly nastavit alarmy nad metrikami dynama.

**Comment by Halama** [comment]
Jde vidět že tím že to tahá jenom jeden malej json tak to v tom dynamu moc nežere.
![image](https://user-images.githubusercontent.com/903531/47158483-0f8fd780-d2ec-11e8-9a27-51dfef3d195b.png)

**Comment by MiroCillik** [comment]
Pozeral som na ten auto-scaling, funguje to dobre, ale tricgy sa obavam, ze to nebude dost rychle.. Realne to zvysi tu propustnost az po 10-15minutach podla tohto clanku:
https://hackernoon.com/the-problems-with-dynamodb-auto-scaling-and-how-it-might-be-improved-a92029c8c10b

Zatial netusim ako bude ta krivka poctu requestov vyzerat. Asi by som to zatial nastavil fixne, potom to mozme sledovat a pripadne zapnut ten auto-scaling a mohlo by nam to usetrit nejake $.

**Comment by MiroCillik** [comment]
Este si sem odlozim 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html#bp-partition-key-throughput-bursting

**Comment by MiroCillik** [comment]
A http://blog.epsagon.com/how-to-handle-aws-lambda-errors-like-a-pro

**Comment by Halama** [comment]
Ok udelejme to fixne, melo by to byt nastavitelne pro kazdy stack separatne takze to nejspis bude v ENV buildu a jako parametr jednotlivych deployu.

**Comment by MiroCillik** [comment]
DynamoDB limity su pripravene: https://github.com/keboola/oauth-api/pull/112

Pozeram na API Gateway rate limity a usage plany. Ono to defaultne zvladne strasne vela requestov za sekundu (10000) aj ked naprice vsetkymi APIckami v API Gateway.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html

Ta domena na ktorej to pobezi `oauth.keboola.com` bude dostupna zvonku? Alebo len nejak v ramci nasho VPC? Len rozmyslam, ze ak bude uplne "public", tak by nam to API mohol niekto prehlcovat requestami a tiez by to zralo $$$. V tom pripade by asi davalo zmysel zaviest nejake API kluce, ktore by dalej mohli mat striktnejsie obmedzenia na pocet requestov za sekundu aby jedno API (OAuth) nezozralo limit pre ostatne..
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html

**Comment by Halama** [comment]
je to public stejně jako developer portal a všechny naše API pro public KBC, kde to myslím taky neřešíme. Je dobré o tom vědět, teď asi řešit nemusíme

**Comment by MiroCillik** [comment]
Ok, suhlasim.

**Comment by MiroCillik** [comment]
Tak to tu mozme zavriet.
