### ISSUE TITLE
Cannot find error in Papertrail

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#110]
Request mi vrátil:
```
* Connection #0 to host oauth.keboola.com left intact
{"errorMessage":"Application Error", "errorType": "ApplicationError", "apiRequestId": "6e93bf07-d2da-11e8-9a62-81620ec11f59"}%   
```

V PT ale nic https://papertrailapp.com/events?q=6e93bf07-d2da-11e8-9a62-81620ec11f59

**Comment by MiroCillik** [comment]
Odlozim si http://blog.epsagon.com/how-to-handle-aws-lambda-errors-like-a-pro

**Comment by MiroCillik** [comment]
Neviem co s tymto, asi by som pockal, ci sa to este objavi a riesil to potom.
