### ISSUE TITLE
Esnerda redirect urls

### ISSUE THREAD

**Issue by MiroCillik** [keboola/oauth-api#121]
David Esner musi pridat redirect urls alebo sa musia zalozit nove a pri migracii reautorizovat:
- [x] esnerda.ex-gmail-csv-downloader
- [x] esnerda.ex-twitter-ads
- [x] esnerda.ex-bingads (US region)

**Comment by Halama** [comment]
Jestli to ma registrované pod sebou tak bych to radši znovu zaregistroval pod náma.

**Comment by Halama** [comment]
Nebo by to mohl přesunout pod nás, u některých služeb to tuším šlo.

**Comment by MiroCillik** [comment]
Napísal som mu email, pretože na Slacku nereaguje. Navrhol som mu aby tie apky presunul pod naše účty, ale to zrejme bude musieť riešiť cez nejaký support.

**Comment by MiroCillik** [comment]
Tak David uz popridaval tie redirect urls, ale chcem este vyskusat, ci to nebude fungovat pre uz existujuce konfiguracie aj s novymi app key a secret. Teda, ze by som tam dal nami vytvorene credentials.
