### ISSUE TITLE
First Release Review

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#13]
## Deployment 
- Přidat template policy s právy které jsou potřeba pro deploy jako https://github.com/keboola/developer-portal/blob/2.38.0/iam-user-template.json#L105
- Nastavuje to zbytečně vělký práva na Dynamo DB, mělo by povolit operace jen na tabulka které mu patří https://github.com/keboola/oauth-api/blob/4233e0ca8a693a809f3cc86b25df3608e65c401a/serverless.yml#L221
- Asi by bylo fajn mít ty parametry dynama parametrizovaný, pro každý stack budou jiný

## Dotazy
- Jakým způsobem vznikne ten `AWS_KMS_KEY_ID`, nemohlo by ho to vytvářet? Jakým způsobem to k němu teď dostane práva?
- Encrypt metoda může zašifrovat jenom 4KB dat, je to ok? Jinak se má používat spíš envelope encryption https://docs.aws.amazon.com/kms/latest/developerguide/workflow.html https://docs.aws.amazon.com/kms/latest/APIReference/API_GenerateDataKey.html

**Comment by Halama** [comment]
co se týče kodu, best practices atd. do toho moc nevidim tak to bych nechal na jakubovi

**Comment by JakubMatejka** [comment]
Zatím vidím: 
- [ ] přesunout `serverless-dynamodb-local`, `sinon`, `unexpected` (tj. moduly pro testy) a `aws-sdk` (který už v aws je) do `devDependencies`, aby se zbytečně nebalily do deploye
- [ ] java v Dockerfile je pro deploy zbytečná, možná zvážit oddělený Docerfile pro testy a pro deploy?
- [ ] chybí cors hlavičky u všech http eventů (https://github.com/keboola/developer-portal/blob/master/serverless.yml#L113)

**Comment by Halama** [comment]
Klidne ale uz ted muzeme zacit zprovoznenim deploye na testing. Ted to ma v travisu vsechny ENV sifrovane tak netusim co tam je, proto bych je vsechny smazal a zacal znovu. Musi se stejne zacit vytvorenim te deploy policy a pak deploy usera ktery bude mit tu policy.

**Comment by JakubMatejka** [comment]
Jj., to už mám taky z vlastní zkušenosti, že na debug je mnohem lepší v Travisu šifrovat jen hesla a tokeny. ;o)

**Comment by MiroCillik** [comment]
@JakubMatejka ty CORS hlavicky tam davam v kode https://github.com/keboola/oauth-api/blob/master/src/functions/authorize.js#L77
Ale asi by sa vacsina dala prehodit do toho serverless.yml

**Comment by MiroCillik** [comment]
@Halama Ten KMS key by asi siel vytvorit priamo v serverless.yml, toto si sem odlozim: https://github.com/serverless/serverless/issues/3892

**Comment by JakubMatejka** [comment]
A jo, sorry, ono to stejně nebude fungovat, já to tam mám zbytečně. ;o) (Serverless v jedný verzi začal podporovat lambda-proxy integraci s API Gatewayí a tam to je zkrátka nutný definovat tak, jak to máš). Ale pokud používáš ten můj RequestHandler, tak ten tam doplní `Access-Control-Allow-Origin: *` (https://github.com/keboola/serverless-request-handler/blob/master/src/index.js#L113)

**Comment by Halama** [comment]
Tyhle defaulty prosim nikde nepouzivat, pak se to nekde zapomene injectout a nebude to fungovat proti jinemu stacku. https://github.com/keboola/oauth-api/blob/4233e0ca8a693a809f3cc86b25df3608e65c401a/src/lib/DockerRunnerApi.js#L14

**Comment by Halama** [comment]
Tady je to koukám taky https://github.com/keboola/oauth-api/blob/4233e0ca8a693a809f3cc86b25df3608e65c401a/src/lib/KbcApi.js#L12

**Comment by Halama** [comment]
Mohlo by ti stačit vyžadovat jenom url KBC a url syrupu si pak sosnout z indexu. Ale nevim jestli ten api call navic nebude brzda.
![image](https://user-images.githubusercontent.com/903531/35922953-40af7d00-0c1f-11e8-871c-1fdc8a4c9225.png)

**Comment by MiroCillik** [comment]
@Halama no, je to trochu otrava :) Zatial by som aj tu Syrup url nechal v env.

**Comment by Halama** [comment]
jo je v pohode, nechme v ENV zatim.

**Comment by Halama** [comment]
za sebe jsem to rozhazel do jednotlivych issues

**Comment by MiroCillik** [comment]
Prehodil som niektore zavislosti do `devDependencies`.

Javu z Dockerfilu vyhadzovat nebudem, to by som musel vytvorit nielen dalsi Dockerfile, ale aj Serverless.yml, kde je plugin `serverless-dynamodb-local`. Sa bojim, ze by v tom bol zmatok. Ked tak by som to nechal do dalsieho refactoringu.

**Comment by JakubMatejka** [comment]
Ok, tak to je jasný. Pak asi můžeme zavřít?

**Comment by MiroCillik** [comment]
JJ.
