### ISSUE TITLE
ex fb ads auth not working after premission update via PATCH

### ISSUE THREAD

**Issue by kacurez** [keboola/oauth-api#138]
Potrebujem upravit permission pre ex fb ads podla navodu v https://sites.google.com/keboola.com/devel-internal/komponenty/oauth/registrovan%C3%A9-oauth-komponenty?authuser=1#h.p_RKY9nri0vIxg a tak
- volam PATCH na `manage/keboola.ex-facebook-ads` a dostavam success vid:
![image](https://user-images.githubusercontent.com/1412120/51243118-fb5a8580-1981-11e9-91da-950b73cebab5.png)

- nasledne skusam autorizovat otvorenim https://oauth.keboola.com/authorize/keboola.ex-facebook-ads a dostanem error:
```
{
"errorMessage": "FB API error: [object Object]",
"requestId": "73cef0f5-6f99-48d8-9962-43f5d04c829a"
}
``` 
V papertrail sa nic viac nedozviem  
![image](https://user-images.githubusercontent.com/1412120/51243277-5f7d4980-1982-11e9-9254-0773db8ee774.png)
Rovnako to dopadne aj ked skusam oauth cez kbc ui.

Podobny postup ale funguje na starom oauth tj 
- zmenim perms cez PATCH:
![image](https://user-images.githubusercontent.com/1412120/51243352-98b5b980-1982-11e9-8710-13cd8c1562d9.png)
- skusam autorizovat cez https://syrup.keboola.com/oauth-v2/authorize/keboola.ex-facebook-ads a dostanem token

### Resume
1. Z `FB API error: [object Object]` sa nedozviem sa kde je chyba(ak som ju urobil ja) 
2. Je mozne ze to nejak rozbije PATCH?

**Comment by kacurez** [comment]
skusal som zmenit version fb api na `v3.1` zmenou v oauth_url a token_url a nezabralo => `FB API error: [object Object]`

**Comment by kacurez** [comment]
btw auth pre "obycajny" facebook funguje:
https://oauth.keboola.com/authorize/keboola.ex-facebook

**Comment by kacurez** [comment]
skusil som to vratit spat na hodnotu ktora tam imo bola predtym s perms `ads_management`

```
{
  
 "auth_url": "https://www.facebook.com/v2.11/dialog/oauth?response_type=code&client_id=%%app_key%%&redirect_uri=%%redirect_uri%%&scope=ads_management"
}
```
ale nezabralo => stale hadze chybu.

Je mozne ze to je zle popisane v dokumentacii ale od pohladu je to imo cajk tak neviem..
https://sites.google.com/keboola.com/devel-internal/komponenty/oauth/registrovan%C3%A9-oauth-komponenty?authuser=1#h.p_RKY9nri0vIxg

**Comment by kacurez** [comment]
este je mozne to porovnat s oauth v EU - tam som nic nemenil a funguje to:
https://oauth.eu-central-1.keboola.com/authorize/keboola.ex-facebook-ads

**Comment by Halama** [comment]
co ten error měl to být teda internal?

**Comment by kacurez** [comment]
myslis to `FB API error: [object Object]`? to imo mal byt aj je user error, pretoze boli ulozene nevalidne `secret` hodnoty, akurat by to este mohlo vypisat ten objekt s konkretnou chybou.
