### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#19]
Unit testy jsem ted musel vypnout protoze ocekavaji nejake nikde nedefinovane AWS resources.
Asi by mi prislo lepsi kdyby vubec nepotrebovali nic z AWS a pouzivali mocky.
Pokud je to fakt potrebuje tak tam musi byt CF stack ktery je nahodit.

Potom by k tomu mohl byt nejaky integracni test, ted se po deploy na testing nedela nic.

Jake jsou best practices pro testovani serverless appek?

**Comment by MiroCillik** [comment]
Unit testy som upravil aby pouzivali lokalne Dynamo DB a mock AWS KMS.
https://github.com/keboola/oauth-api/pull/29

A ako pises na tie Serverless funkcie by mohli byt este integracne testy pomocou `serverless invoke` ako pisu tu dole https://serverless.com/framework/docs/providers/aws/guide/testing/

**Comment by MiroCillik** [comment]
Na integracne testy som zalozil samostatnu issue https://github.com/keboola/oauth-api/issues/30.

Unit tests fixed in https://github.com/keboola/oauth-api/pull/29
