### ISSUE TITLE
Facebook has different fields in Manage POST

### ISSUE THREAD

**Issue by MiroCillik** [keboola/oauth-api#2]
```
{
    "component_id": "keboola.ex-facebook",
    "friendly_name": "Facebook Extractor",
    "app_key": "xxx",
    "app_secret": "xxx",

    "oauth_version": "facebook",
    "permissions": "public_profile,read_insights,pages_show_list"
}
```

`oauth_version` must be mapped to `token_url`
`permissions` to `auth_url`

**Comment by MiroCillik** [comment]
See https://github.com/keboola/oauth-v2-bundle/blob/master/Controller/ManageController.php#L181

**Comment by kacurez** [comment]
este tam je optional `graph_api_version` s default na `v2.8`

**Comment by MiroCillik** [comment]
I have decided, thah Facebook will be using the same fields as classic OAuth 2.0. See https://github.com/keboola/oauth-api/commit/bbffce1181f9129a1b8dbd235b909fcead30446a
