### ISSUE TITLE
Remove ACCOUNT_ID from env

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#21]
Není k ničemu potřeba, tady https://github.com/keboola/oauth-api/blob/76e26157b414301bc3078f5f6b2dda46111958e7/serverless.yml#L213 ho můžeš získat pomocí funkcí Cloudformation https://serverless.com/blog/abcs-of-iam-permissions/

**Comment by JakubMatejka** [comment]
Tady je hotová: https://github.com/keboola/gooddata-provisioning-api/blob/master/serverless.yml#L216

**Comment by MiroCillik** [comment]
Done in https://github.com/keboola/oauth-api/pull/29/commits/9fe458df9fd3121cde5d5a7d7ccbb9f75eb12eee
