### ISSUE TITLE
Create KMS keys in serverless resources

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#22]
Založit klíč v serverless resources a lambda roli přidat práva pro jeho používání 
https://github.com/keboola/oauth-api/blob/76e26157b414301bc3078f5f6b2dda46111958e7/serverless.yml#L189

Inspirace tady https://github.com/keboola/syrup-router/pull/81/files#diff-cccea4808eb52ddcf68f4dac868eaa35 U toho KMS klice je trik v tom ze mu prvni musis dat Resource  policy která umožní accountu nad ním spravovat IAM.

**Comment by MiroCillik** [comment]
Solved in https://github.com/keboola/oauth-api/pull/29
