### ISSUE TITLE
Hardcoded KBC and Syrup URLs

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#23]
https://github.com/keboola/oauth-api/blob/4233e0ca8a693a809f3cc86b25df3608e65c401a/src/lib/DockerRunnerApi.js#L14

https://github.com/keboola/oauth-api/blob/4233e0ca8a693a809f3cc86b25df3608e65c401a/src/lib/KbcApi.js#L12

Mělo by se přesunout do ENV, teďka to nefunguje v EU.

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/oauth-api/pull/29/commits/b171bbfa297017a3963f06574f8aa320f03eda72 and https://github.com/keboola/oauth-api/pull/29/commits/ea03920f92e2638bdb28ffdba000d58fc2a6879d
