### ISSUE TITLE
Unused REGION env

### ISSUE THREAD

**Issue by Halama** [keboola/oauth-api#24]
Tady https://github.com/keboola/oauth-api/blob/76e26157b414301bc3078f5f6b2dda46111958e7/serverless.yml#L29 a dále není potřeba. 
Je potřeba jí jenom předat do https://github.com/keboola/oauth-api/blob/76e26157b414301bc3078f5f6b2dda46111958e7/serverless.yml#L22

**Comment by JakubMatejka** [comment]
Řek bych, že je. `provider.environment` se předává do lambdy a tam se to používá třeba tady: https://github.com/keboola/oauth-api/blob/master/src/lib/DynamoDB.js#L24
