### ISSUE TITLE
upgrade na Node 8

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#38]

**Comment by MiroCillik** [comment]
Aaa, ono uz to umi Node 8 nejaky cas. Ok.
https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

**Comment by MiroCillik** [comment]
Updatnute, spolu s dalsimi deps https://github.com/keboola/oauth-api/pull/41
