### ISSUE TITLE
Convert app secret to base64

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#51]
😄 
<img width="602" alt="oauth-api 2018-08-02 19-51-57" src="https://user-images.githubusercontent.com/215660/43601569-cab84c4a-968d-11e8-9f7e-3b9dd2015c65.png">

**Comment by MiroCillik** [comment]
Á ha :D

**Comment by JakubMatejka** [comment]
@MiroCillik teď se mi to nějak nedaří domyslet, je ok, že se ten app secret vrací rozšifrovanej, jo?

**Comment by MiroCillik** [comment]
@JakubMatejka a jo, pozeram, ze v starom to vracia zasifrovane. Spravim to teda tak.

**Comment by MiroCillik** [comment]
Doprdele, mne tam chyba to `app_secret_docker` vlastne.. Tss https://oauthv2.docs.apiary.io/#reference/manage/deletegetupdate-api-detail/get-api-detail

**Comment by MiroCillik** [comment]
To musi tak ako tu https://github.com/keboola/oauth-api/blob/master/src/app/Authorize.js#L126
