### ISSUE TITLE
Create credentials fails

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#52]
<img width="594" alt="2 docker-compose run --rm --service-ports dev docker 2018-08-02 20-06-11" src="https://user-images.githubusercontent.com/215660/43602222-a1c16acc-968f-11e8-8d86-294c97e2364a.png">

**Comment by MiroCillik** [comment]
@JakubMatejka  Tak problem je inde. Mas spravne nastavenu DOCKER_RUNNER_URL? Pretoze zda sa, ze chyba vznikne pri enkryptovani dat cez docker-runner.

Aha, uz to vidim, chyba to v README.md. Doplnil som to tam.

`DOCKER_RUNNER_URL=https://docker-runner.keboola.com`

**Comment by JakubMatejka** [comment]
Aha, neměl jsem. Už to funguje
