### ISSUE TITLE
List, get & delete of credentials returns 400

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#53]
<img width="579" alt="oauth-api 2018-08-02 20-12-40" src="https://user-images.githubusercontent.com/215660/43602538-8254d7fe-9690-11e8-850f-2b271e47a911.png">

**Comment by JakubMatejka** [comment]
Aha, to neměl být detail ale výpis. Nicméně na detail pro existující i neexistující credentials (http://0.0.0.0:3030/credentials/keboola.ex-twitter/test1) to vrací taky 400.

**Comment by MiroCillik** [comment]
Tu 400ku ti to hadzalo kvoli inej chybe, normalne by to malo vratit 404 https://monosnap.com/file/dUiiu2sHfYRntbLEn8uhzwCqBehRWr.

Ale este to cele preklikam pre istotu.

**Comment by MiroCillik** [comment]
Vyzera to dobre, vyskusaj este raz. Myslim, ze to bolo sposobene tou chybajucou ENV `DOCKER_RUNNER_URL`. viz https://github.com/keboola/oauth-api/issues/52
