### ISSUE TITLE
Get credentials fails with error

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#70]
<img width="716" alt="oauth-api 2018-08-19 21-24-58" src="https://user-images.githubusercontent.com/215660/44312321-809f3580-a3f6-11e8-9a44-d9d2eda9ea36.png">

**Comment by MiroCillik** [comment]
Hm, toto mi funguje, aj ked tam credentials su aj ked tam nie su, tak to hodi spravnu hlasku. Ja som menil nejake drobnosti v CloudFormation template, tak mozno si to skus updatnut. Ak by sa ti chcelo :)

**Comment by JakubMatejka** [comment]
Pořád to samý. ;o/ Ale tak možná je to tím lokálem, zkusím to deploynout. A jak tak koukám na ten stack trace, nemělo by se tomu offline pluginu vysvětlit, že má použít source mapy? (tzn. aby neukazoval na zwebpackovanej kód - /code/.webpack/service/src/functions/credentials.js:2830:26 - ale na původní zdroják)

![oauth-api 2018-08-31 08-53-47](https://user-images.githubusercontent.com/215660/44897310-81d83880-acfb-11e8-9d90-f8ed77d6addd.png)

**Comment by MiroCillik** [comment]
Ja to prave tiez skusam na lokale :/ Este na to pozriem. A to s tymi source mapami, to som nevedel, ze to takto moze fungovat! Na to sa tiez pozriem teda :) Diky

**Comment by JakubMatejka** [comment]
Jj. díky tomu v produkci vidíme stacktrace nad původníma zdrojákama. Akorát nevím jak je to s tím offline pluginem, já ho moc nepoužíval.
Jinak ta chyba vznikla tady:
![credentials js 2018-08-31 09-04-19](https://user-images.githubusercontent.com/215660/44897784-2dce5380-acfd-11e8-8539-2deac0fa3ef1.png)
Je to sice mírně zdeformovaný tím webpackem, ale je to nejspíš odtud: https://github.com/keboola/oauth-api/blob/6bb0622afdcbee6f380718206f09da8536181189/src/lib/KbcApi.js#L66 (tzn. v `err` není `response`, ale to je jen chyba v error handlingu, ne důvod proč to failuje ;o)

**Comment by MiroCillik** [comment]
Ja uz som sa s touto chybou stretol predtym. Vyzera to teda na neplatny SAPI token.. Vyskusam a pripadne upravim tu chybovu hlasku.

**Comment by JakubMatejka** [comment]
Hm, tak token je ok
![storage api 2018-08-31 10-26-58](https://user-images.githubusercontent.com/215660/44901715-75a6a800-ad08-11e8-9d10-67b01df0e98a.png)

**Comment by JakubMatejka** [comment]
Ha, už vím. Mám v hlavičce `X-StorageApiToken` namísto `X-StorageApi-Token`

**Comment by MiroCillik** [comment]
Jo, je to tym tokenom, upravim ten catch.

**Comment by MiroCillik** [comment]
Este by to mozno chcelo test na toto.

**Comment by MiroCillik** [comment]
Teraz by to uz malo hadzat spravne hlasky https://github.com/keboola/oauth-api/pull/75
