### ISSUE TITLE
Delete credentials fails with error

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/oauth-api#71]
<img width="449" alt="1 docker-compose run --service-ports app docker 2018-08-19 21-28-39" src="https://user-images.githubusercontent.com/215660/44312346-e390cc80-a3f6-11e8-854e-5de70db8fcb0.png">

**Comment by MiroCillik** [comment]
Toto mi tiez funguje. Aj s neexistujucimi credentials.

**Comment by JakubMatejka** [comment]
Zkouším teď na deploynutý službě v awsku a zdá se, že tady: https://github.com/keboola/oauth-api/blob/17d4ac6547e413e5c2e787f1d15f34d3a7b65223/serverless.yml#L254 chybí permission na `DeleteItem`

![image](https://user-images.githubusercontent.com/215660/44902334-00d46d80-ad0a-11e8-8f4e-4a9d983c0333.png)

**Comment by MiroCillik** [comment]
Zajimave, diky, skusim deploynut tiez.
